export default {
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '1f391b9e': [() => import(/* webpackChunkName: '1f391b9e' */ '@theme/MDXPage'), '@theme/MDXPage', require.resolveWeak('@theme/MDXPage')],
  '393be207': [() => import(/* webpackChunkName: '393be207' */ '@site/src/pages/markdown-page.md'), '@site/src/pages/markdown-page.md', require.resolveWeak('@site/src/pages/markdown-page.md')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '831de094': [() => import(/* webpackChunkName: '831de094' */ '@site/docs/review.md'), '@site/docs/review.md', require.resolveWeak('@site/docs/review.md')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  '9c6f1cd0': [() => import(/* webpackChunkName: '9c6f1cd0' */ 'D:\\Git_repo\\zcxxxxxxx.github.io\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json'), 'D:\\Git_repo\\zcxxxxxxx.github.io\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json', require.resolveWeak('D:\\Git_repo\\zcxxxxxxx.github.io\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json')],
  'bb8996fe': [() => import(/* webpackChunkName: 'bb8996fe' */ '@site/docs/JAVA_review.md'), '@site/docs/JAVA_review.md', require.resolveWeak('@site/docs/JAVA_review.md')],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ '@site/src/pages/index.js'), '@site/src/pages/index.js', require.resolveWeak('@site/src/pages/index.js')],
  'c7df7655': [() => import(/* webpackChunkName: 'c7df7655' */ 'D:\\Git_repo\\zcxxxxxxx.github.io\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json'), 'D:\\Git_repo\\zcxxxxxxx.github.io\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json', require.resolveWeak('D:\\Git_repo\\zcxxxxxxx.github.io\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json')],};
